---
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Elliot Routier's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Elliot Routier
headline: Mechanical Engineer at the University of Bath
description: >- # dont remove this line. this will ignore all new lines until the next section
  I'm Elliot Routier, a Mechanical Engineering student at the University of Bath with a 
  passion for cutting-edge tech, engineering, and clean design. From designing drone components 
  for Team Bath Drones to exploring AI-driven robotics during my internship in France, 
  I thrive at the intersection of creativity and engineering precision. I’m always looking 
  for my next challenge — whether it's taking part in the Shell Eco Marathon, coding a chess 
  game from scratch, or designing miniature train parts in CAD.
  Let's build something remarkable.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/elliot.jpg


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume-url: ./assets/documents/Routier_Elliot_CV_Bath_MechEng.pdf # https://drive.google.com/file/d/1SY625bdNk7aXD_J4Pb-eWsEtZD1CGjgz/view?usp=drive_link


# Set up external links - this will show up as small icons next to your name.
external-links:
  linkedin: https://www.linkedin.com/in/elliot-routier/
  github: https://github.com/elliotroutier
  outlook: mailto:er909@bath.ac.uk
  #stackoverflow:   https://stackoverflow.com/users/your-slug
  #medium:          https://medium.com/@your-slug
  #x-twitter:       https://x.com/your-slug 
  #threads:         https://threads.net/@your-slug
  #instagram:       https://instagram.com/your-slug
  #youtube:         https://youtube.com/@your-slug
  #discord:         https://discord.com/users/your-slug
  #bluesky:         https://bsky.app/profile/your-slug

  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: 3D Modeling
    tools:
    - Inventor (Autodesk)
    - Solidworks
    - Fusion 360 (Autodesk)
  - category: Prototyping
    tools:
    - Lathe
    - FDM
    - Laser Cutting
    - Arduino
    - Breadboarding
    - Soldering
  - category: IT Skills
    tools:
    - Python
    - MATLAB
    - Simulink
    - JavaScript
    - HTML / CSS
    - Git / GitHub (version control)
    - Word
    - PowerPoint
    - Excel
    - Generative AI
  - category: Finite Element Analysis
    tools:
    - Ansys
  - category: Risk Management / Engineering Principles
    tools:
    - FTA (Fault Tree Analysis)
    - DFMEA / DFMA
    - UML Activity Diagrams
    - DFM (Design For Manufacturing)
    - Technical Drawings
  - category: Languages
    tools:
    - English (native)
    - French (fluent)
    - German (proficient)
    - Spanish (basic)
  - category: Professional Skills
    tools:
    - Communication
    - Teamwork
    - Time Management
    - Leadership
    - Interpersonal
    


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/mvgrprqq



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
